- hosts: all
  become: yes
  tasks:
    - name: Atualiza o cache do apt
      apt:
        update_cache: yes
      tags:
        - packages

    - name: Instala o Nginx
      apt:
        name: nginx
        state: present
      tags:
        - packages

    - name: Copia a página web para o diretório do Nginx
      copy:
        src: files/
        dest: /usr/share/nginx/html
        owner: www-data
        group: www-data
        mode: "0644"
      notify:
        - Reiniciar Nginx
    
    - name: Copia HTML template
      template:
        src: files/index.html.j2
        dest: /usr/share/nginx/html/index.html
        owner: www-data
        group: www-data
        mode: "0644"
    
    - name: Copia CSS template
      template:
        src: files/assets/css/style2.css.j2
        dest: /usr/share/nginx/html/assets/css/style.css
        owner: www-data
        group: www-data
        mode: "0644"

  handlers:
    - name: Reiniciar Nginx
      service:
        name: nginx
        state: restarted
